config/routes.rb
StackFlow::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  post '/new_message' => 'chats#new_message', :as => :new_message
  match 'chats/select_chat_friend/:id' => 'chats#select_chat_friend'

  root :to => "questions#full_view"
  match 'answers/user_chance_question' => 'answers#user_chance_question'
  match 'questions/points/:id' => 'questions#points'
  match 'questions/unlike/:id' => 'questions#unlike'
  match 'questions/full_view' => 'questions#full_view'
  match 'questions/per_subject_questions/:id' => 'questions#per_subject_questions'
  match 'questions/tags' => 'questions#tags', :as=>:question_tags
  match 'questions/tag_search' => 'questions#tag_search'
  match 'chats/chating_status' => 'chats#chating_status'

  resources :chats do
        collection do
           get 'admin_search'
        end
  end
  resources :questions
  resources :answers do
        member do
           post 'create_user_comment'
        end
  end

  resources :comments

end

app/views/shared/_bottom_header.html.erb
<div class="bottom-sub-wrap">
        <%= image_tag("stack.jpg", :size => "50x50")%>
        <span> Stack Flow </span>
</div>

app/views/shared/_top_header.html.erb
 <div class="top-sub-wrap">
        <%= image_tag("stack.jpg", :size => "65x65")%>
        Stack Flow
        <span style="font-size:14px; font-family:arial;"> We answer you </span>
        <span class="current-admin">
                <% if admin_signed_in? %>
                       You are logged in as:  <%= link_to current_admin.email, edit_admin_registration_path, :title=>"You want to edit", :style => 'color:white; text-decoration:none;' %>
                <%else%>
                        <%= link_to "Register Now",  new_admin_registration_path, :class=>"top-link" %>
                <%end%>
        </span>
 </div>

app/views/shared/_top_links.html.erb
<ul>
        <li>
                <%= link_to "Full view", "/questions/full_view", :class=>"top-link" %> &nbsp;&nbsp;
        </li>
        <li>
                <%= link_to "Questions", questions_path(), :class=>"top-link" %> &nbsp;&nbsp;
       </li>
       <li>
                <%= link_to "Answers", answers_path(), :class=>"top-link" %> &nbsp;&nbsp;
        </li>
       <li>
                <%= link_to "Ask question", new_question_path(), :class=>"top-link" %> &nbsp;&nbsp;
       </li>
       <li>
                <%= link_to "My answer",  new_answer_path(), :class=>"top-link" %> &nbsp;&nbsp;
        </li>
        <li>
                <%= link_to "Tags",  question_tags_path, :class=>"top-link" %> &nbsp;&nbsp;
        </li>
        <li>
                <% if admin_signed_in? %>
                        <%= link_to "Unanswered",{:controller=>"questions", :action=>"index", :un_answered=>"un_answered"}, :class=>"top-link" %> &nbsp;&nbsp;
                <% end %>
        </li>

        <li>
                <% if admin_signed_in? %>
                        <%= link_to "Chat",  chats_path, :class=>"top-link" %> &nbsp;&nbsp;
                <% else %>
                       <%= link_to "Chat",  "#",:remote=>true, :onclick=>"show_popup()",:class=>"top-link" %> &nbsp;&nbsp;
                <% end %>
        </li>

        <li>
                <%  if admin_signed_in?%>
                        <%= link_to "Sign out", destroy_admin_session_path(), :method=>"delete", :class=>"top-link" %> &nbsp;&nbsp;
                <%else%>
                        <%= link_to "Sign in", new_admin_session_path(), :class=>"top-link" %> &nbsp;&nbsp;
                <%end%>
        </li>
</ul>

<script>
    function show_popup()
    {
        $('#display_popup').show('slow');
        $('#content').css('opacity','0.5');
        $('#close_pop').click(function(){$('#display_popup').hide('slow');$('#content').css('opacity','1');});
    }
</script>