config/routes.rb
StackFlow::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  devise_for :admins

  mount Ckeditor::Engine => '/ckeditor'

  post '/new_message' => 'chats#new_message', :as => :new_message
  match 'chats/select_chat_friend/:id' => 'chats#select_chat_friend'

  root :to => "questions#full_view"
  match 'answers/user_chance_question' => 'answers#user_chance_question'
  match 'questions/points/:id' => 'questions#points'
  match 'questions/unlike/:id' => 'questions#unlike'
  match 'questions/full_view' => 'questions#full_view'
  match 'questions/per_subject_questions/:id' => 'questions#per_subject_questions'
  match 'questions/tags' => 'questions#tags', :as=>:question_tags
  match 'questions/tag_search' => 'questions#tag_search'
  match 'chats/chating_status' => 'chats#chating_status'

  resources :chats do
        collection do
           get 'admin_search'
        end
  end
  resources :questions
  resources :answers do
        member do
           post 'create_user_comment'
        end
  end

  resources :comments

end

app/models/chat.rb
class Chat < ActiveRecord::Base
        validates :sender_name, :presence => true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
        before_filter :authenticate_admin!, :only => [:create, :index]
        respond_to :js, :only=>[:admin_search, :chating_status, :select_chat_friend]

        def index
                session[:username] = current_admin.name_of_admin
                @chat_status = Admin.find(current_admin.id)
                @chat_status.update_attribute(:chat_status, "active")
                @all_admins_in_chat = Admin.find_all_by_chat_status("active")
        end

        def admin_search
                if !params[:name_of_admin].blank? && params[:name_of_admin].length > 1
                        if params[:name_of_admin][0]=="@"
                                @all_admins = Admin.find(:all, :conditions => ["name_of_admin LIKE ?", "#{params[:name_of_admin][1..params[:name_of_admin].length]}%"])
                        else
                                @all_admins = Admin.find(:all, :conditions => ["name_of_admin LIKE ?", "#{params[:name_of_admin]}%"])
                        end
                else
                        @all_admins = []
                end
        end

        def chating_status
                @chat_status = Admin.find(current_admin.id)
                @chat_status.update_attribute(:chat_status, params[:chat_status])
                render :text => "".inspect and return false
        end

        def select_chat_friend
               #render :text=> params.inspect and return false
               @chat_status = Admin.find(current_admin.id)
               @chat_status.update_attribute(:chat_friend_name , params[:id])
               @find_admin = Admin.find_by_name_of_admin(@chat_status.chat_friend_name)
               @find_admin.update_attribute(:chat_friend_name , current_admin.name_of_admin)
               @chat_friend_name = @chat_status.chat_friend_name
               @channel = "/messages/private/#{params[:id]}"
               @local_channel = "/messages/private/#{session[:username]}"

               @local_message = { :sender => @chat_status.chat_friend_name, :username => @find_admin.chat_friend_name,
               :msg => "requested to chat with #{ @chat_status.chat_friend_name}" , :content=>"<div id='#{@chat_status.chat_friend_name}_1'
               style='height:200px; width:250px;overflow-y:scroll; float:left;outline:1px solid #B930B9; background:white;'>
                <i class='link_to_text2' id='#{@chat_status.chat_friend_name}_2'>#{@chat_status.chat_friend_name}</i>
                <form method='post' data-remote='true' action='/new_message' ><input type='hidden' name='cval' value='#{@chat_status.chat_friend_name}'/>
                <input type='text' name='message' class='chat_text' /></form>  </div>" }

               @message = {:sender => @find_admin.chat_friend_name, :username => @find_admin.chat_friend_name,
               :msg => "wants to chat", :content=>"<div id='#{session[:username]}_1'
               style='height:200px; width:250px;overflow-y:scroll; float:left;outline:1px solid #B930B9; background:white;'>
               <i class='link_to_text2' id='#{session[:username]}_2'>#{session[:username]}</i>
               <form method='post' data-remote='true' action='/new_message' ><input type='hidden' name='cval' value='#{session[:username]}'/>
               <input type='text' name='message' class='chat_text' /></form> </div> " }

        end

        def new_message
                #if !current_admin.chat_friend_name.nil? && !current_admin.chat_friend_name.blank?
                    @name = Admin.find_by_name_of_admin(current_admin.chat_friend_name)
                    if @name.chat_status=="active"

                            @local_channel = "/messages/private/#{session[:username]}"
                            @local_message = {:sender=>params[:cval], :username => session[:username], :msg => params[:message] }
                            #@channel = "/messages/private/#{splt.first.gsub(/@/, '')}"
                            @channel = "/messages/private/#{params[:cval]}"
                            @message = {:sender=>session[:username], :username => session[:username], :msg => params[:message] }
                    else
                            @channel = "/messages/public"
                            @message = { :username => session[:username], :msg => params[:message] }
                    end
                #else
                     # @channel = "/messages/public"
                     # @message = { :username => session[:username], :msg => params[:message] }
                #end
                respond_to do |f|
                        f.js
                end
        end
end

app/helpers/chats_helper.rb
module ChatsHelper
=begin
        def requested_friend()
                @all = Admin.find_all_by_chat_friend_name(current_admin.name_of_admin)
                @names = @all.map{|a| a.name_of_admin}
                return @names
        end
=end
end

app/views/chats/_admin_names.html.erb
<% @all_admins.each do |ad| %>
   <div id="<%= ad.name_of_admin %>" onclick="$('#message').val('@'+this.id); $('#admins_area').hide();" onmouseover="$(this).css('background','yellow');" onmouseout="$(this).css('background','white');" style="padding:3px; border:0.2px solid grey; color:green; font-size:12px;" >
       <%= link_to ad.name_of_admin, '#', :style=>'color:green; font-size:12px;text-decoration:none;' %>
       <%#= ad.name_of_admin %>
   </div>
<% end %>

app/views/chats/_chat_content.html.erb
<% @chats.each do |ch|%>
        <div style="color:black; font-size:12px;padding-left:10px;">
              <%= ch.content %>
        </div>
        <div style="color:#F9092D; font-size:13px;padding-left:10px;">
             <span style="color:grey; font-size:10px;"> Sent by:</span>
             <%= ch.sender_name %>
        </div>
        <div style="height:10px; margin-left:0px;"></div>
        <hr />
<%end%>

app/views/chats/admin_search.js.erb
$("#admins_area").html("<%= escape_javascript(render "admin_names")%>")

app/views/chats/chating_status.js.erb
 $("#chat_status").html('<%= escape_javascript( @chat_status.chat_status ) %>');

app/views/chats/index.html.erb
<div class="top_links">
        <%= render "/shared/top_links" %>
</div>
<div  class="sub-mid-wrap" style="background:white; height:auto;">
        <ul>
                <li id="blue" style="cursor:pointer; color:blue;"> <%= image_tag('/assets/MaroonBall.png')%> &nbsp;&nbsp;&nbsp; </li>
                <li id="red" style="cursor:pointer; color:red;"> <%= image_tag('/assets/RedBall.png')%> &nbsp;&nbsp;&nbsp; </li>
                <li id="green" style="cursor:pointer; color:green;"> <%= image_tag('/assets/GreenBall.png')%> &nbsp;&nbsp;&nbsp; </li>
        </ul>
        <div>
                <%= select_tag("chat_status",options_for_select([["#{current_admin.chat_status}","#{current_admin.chat_status}"],["active","active"],["inactive","inactive"],["invisable","invisable"]]))%>
        </div>

        <div style="padding-left:10px; background:white; ">

                <div id="chat_head" class="chat_head_blue">
                      Chat Room:
                </div>
                <div style="height:10px;"></div>

               <div style="">
                        <div id="change2" >
                           <h5 class="alert" >
                                  Welcome to the chat:
                                  <span style="color:#118F93;"> <%= session[:username] %>! </span>
                           </h5>


                          <!-- <div id="chat_room" class="change_blue" style="width:50%; display:none;">
                                <div class="link_to_text" id="head1" ></div>
                           </div>

                           <div id="chat_room2" class="chat_change">
                                <div class="link_to_text"  id="head2"></div>
                           </div> -->

                           <div style="position:relative; ">
                              <div id="all_admins_in_chat" >
                                 <% @all_admins_in_chat.each do |c|%>
                                    <div id="<%= c.name_of_admin %>" class="link_text" >
                                      <% if current_admin.name_of_admin != c.name_of_admin %>
                                            <%= link_to c.name_of_admin, "/chats/select_chat_friend/#{c.name_of_admin}" , :remote => true, :class=>"link_decoration"  %>
                                            &nbsp;&nbsp;&nbsp;&nbsp; <span class="online_status"> :online </span>
                                      <%end%>
                                    </div>
                                 <%end%>
                              </div>
                          </div>
                       </div>
               </div>
              <!-- <div id="chat_form" class ="chat_form_blue">
                        <%#= form_tag new_message_path, :remote => true do %>
                                <%#= text_field_tag :message,params[:message], :placeholder => "Write something and hit enter..!", :class => "text_blue", :style=>"width:48%;" %>
                                <%#= submit_tag "Send" %>
                        <%# end %>
                        <div id="admins_area" class ="admins_area_blue" >
                        </div>
               </div> -->

               <div style="height:20px;"></div>

        </div>
</div>

<%= subscribe_to "/messages/public" %>
<%= subscribe_to "/messages/private/#{session[:username]}" %>

<script type="text/javascript">

        PrivatePub.subscribe("/messages/public", function(data) {

          if(data.msg.indexOf(":)") != -1  || data.msg.indexOf(":-)") != -1 )
                {
                        data.msg = data.msg.replace(/\W[:,),-]/g, '<img src="/assets/Smile3.png">').replace(/\W[')']/g, '');
                }

        if(data.msg.indexOf(":smile")!=-1)
                {
                       data.msg = data.msg.replace(/:smile/g, '<img src="/assets/Smile3.png" alt="love">');
                }

         if(data.msg.indexOf("(:")!=-1 || data.msg.indexOf(":(")!=-1 || data.msg.indexOf(":-(")!=-1)
                {
                        data.msg = data.msg.replace(/\W[:,(,-]/g, '<img src="/assets/tong_smile.gif" alt="tounge smile">').replace(/\W['(']/g, '');
                }

         if(data.msg.indexOf(":D")!=-1)
                {
                        data.msg = data.msg.replace(/:D/g, '<img src="/assets/Face_Awesome.png" alt="love">');
                }

         $('<p></p>').html("<span style='color:red; font-size:12px; font-style:italic;padding-left:5px; '>"+ data.username + " says : </span>" +"<span style='color:blue; font-size:13px; font-style:normal; padding-left:0px;'>"+ data.msg+ "</span>").appendTo('#chat_room');

         $("#chat_room").scrollTop($("#chat_room  > p").size() * 40);

          $('#message').val("");
       });
//
        //Private messages
//

        PrivatePub.subscribe("/messages/private/<%= session[:username] %>", function(data) {

          if(data.msg.indexOf(":)")!=-1  || data.msg.indexOf(":-)")!=-1 )
                {
                        data.msg = data.msg.replace(/\W[:,),-]/g, '<img src="/assets/Smile3.png">').replace(/\W[')']/g, '');
                }

        if(data.msg.indexOf(":smile")!=-1)
                {
                       data.msg = data.msg.replace(/:smile/g, '<img src="/assets/Smile3.png" alt="love">');
                }

         if(data.msg.indexOf("(:")!=-1 || data.msg.indexOf(":(")!=-1 || data.msg.indexOf(":-(")!=-1)
                {
                        data.msg = data.msg.replace(/\W[:,(,-]/g, '<img src="/assets/tong_smile.gif" alt="tounge smile">').replace(/\W['(']/g, '');
                }

         if(data.msg.indexOf(":D")!=-1)
                {
                        data.msg = data.msg.replace(/:D/g, '<img src="/assets/Face_Awesome.png" alt="love">');
                }
        //alert(data.sender+'_1')
         $('<p></p>').addClass('private').html("<span style='color:red; font-size:12px; font-style:italic;padding-left:5px;'>"

         +data.username + " says : </span>" +"<span style='color:blue; font-size:13px; font-style:normal; padding-left:0px;'>"
         + data.msg+ "</span>").appendTo('#'+data.sender+'_1');

         if($("i > "+data.content).html() != data.sender){
                $(data.content).appendTo('#change2');
         }
         $('#'+data.sender+'_1').scrollTop($('#'+data.sender+'_1 > p').size() * 40);

          $('#'+data.username).val("");
        });
        $(".link_decoration").bind("ajax:success", function(event, data, status, xhr) {
              eval(data);
        });

</script>

app/views/chats/new_message.js.erb
<%= publish_to @channel, @message %>
<%= publish_to @local_channel, @local_message %>

app/views/chats/select_chat_friend.js.erb
<% publish_to @channel, @message %>

<% publish_to @local_channel, @local_message %>